force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</description>
    <inlineHelpText>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>A unique name to reference this record by without knowing its ID. This is particularly useful when invoking a configuration on-demand from Process Builder or Flow.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique name to reference this record by without knowing its ID.</inlineHelpText>
    <label>Mass Action Configuration Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Last_Run_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Completed_Date__c</fullName>
    <description>When the last run of this configuration completed. It is updated when the batch job finishes. Use this field to control when you chain other configurations together. For example, Process Builder may monitor when this field value changes and if the unique name is "Config1" then can decide to automatically run "Config2" to ensure "Config2" only runs after "Config1" completes.</description>
    <inlineHelpText>When the last run of this configuration completed. It is updated when the batch job finishes. Use this field to control when you chain other configurations together. For example, to ensure "Config2" only runs after "Config1" completes.</inlineHelpText>
    <label>Last Run Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Last_Run_Completed_With_Errors__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Completed_With_Errors__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the last run of this configuration completed with errors. It is updated when the batch job finishes. This field is checked if the last run of this configuration created log records reporting any errors, otherwise it is unchecked. Use this field with the Last Run Completed Date in Process Builder to control when to automatically run other configurations conditionally upon a configuration completing successfully or not. For example, run &quot;Config2&quot; only if &quot;Config1&quot; completed without errors.</description>
    <inlineHelpText>Indicates if the last run of this configuration completed with errors. It is updated when the batch job finishes. This field is checked if the last run of this configuration created log records reporting any errors, otherwise it is unchecked.</inlineHelpText>
    <label>Last Run Completed With Errors</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named Credential that provides authentication to Salesforce REST API when invoking target actions. This will be the context user for the record updates.</description>
    <inlineHelpText>By default, the user who schedules the mass actions is the context user for record updates. You may optionally choose a Named Credential to specify the context user instead.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_SOQL_Query__c.field-meta.xml
<CustomField>
    <fullName>Source_SOQL_Query__c</fullName>
    <description>SOQL query that provides the source records. Applicable when Source Type is SOQL. Max SOQL query length limit: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm</description>
    <inlineHelpText>Enter SOQL query that identifies the records to process. Use aliases with Aggregate functions (COUNT, SUM, MIN, MAX, AVG, etc.) to make them available in the Field Mappings step.</inlineHelpText>
    <label>Source SOQL Query</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>Where source records come from to perform actions on, like reports or list views.</description>
    <inlineHelpText>Where source records come from to perform actions on, like reports or list views.</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Action_Name__c</fullName>
    <description>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</description>
    <inlineHelpText>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</inlineHelpText>
    <label>Target Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_SObject_Type__c</fullName>
    <label>Target SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <description>Type of action to perform on the source records.</description>
    <inlineHelpText>Type of action to perform on the source records.</inlineHelpText>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
                <label>Process Builder &amp; Flows</label>
            </value>
            <value>
                <fullName>Workflow</fullName>
                <label>Workflow Rules</label>
            </value>
            <value>
                <fullName>QuickAction</fullName>
                <label>Quick Actions</label>
            </value>
            <value>
                <fullName>EmailAlert</fullName>
                <label>Email Alerts</label>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/Mass_Action_Log__c.object-meta.xml
<CustomObject>
    <description>Information about Mass Action batch job executions. You can safely delete these records after their related batch job has finished.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Log</label>
    <nameField>
        <displayFormat>MAL-{000000}</displayFormat>
        <label>Mass Action Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/Mass_Action_Mapping__c.object-meta.xml
<CustomObject>
    <description>Defines field mappings between sources and targets.</description>
    <label>Mass Action Mapping</label>
    <nameField>
        <displayFormat>MAM-{000000}</displayFormat>
        <label>Mass Action Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Mappings</relationshipLabel>
    <relationshipName>Mass_Action_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Source_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Name__c</fullName>
    <description>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</description>
    <inlineHelpText>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</inlineHelpText>
    <label>Source Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <description>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</description>
    <inlineHelpText>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</inlineHelpText>
    <label>Target Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MA_SoqlSourceBatchableTest.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
@IsTest
private class MA_SoqlSourceBatchableTest {

    @IsTest
    static void test_batchable_Workflow() {

        test_batchable( 'Workflow', null, 'Account' );

    }

    @IsTest
    static void test_batchable_Flow() {

        test_batchable( 'Flow', 'Test_Flow', null );

    }

    @IsTest
    static void test_batchable_QuickAction() {

        test_batchable( 'QuickAction', 'Test_Quick_Action', 'Account' );

    }

    @IsTest
    static void test_batchable_EmailAlert() {

        test_batchable( 'EmailAlert', 'Test_Email_Alert', 'Account' );

    }

    @IsTest
    static void test_batchable_Apex() {

        test_batchable( 'Apex', 'Test_Apex', null );

    }

    static void test_batchable( String targetType, String targetActionName, String targetSobjectType ) {

        String objectName = MA_MassActionUtils.NAMESPACE_API + 'Mass_Action_Configuration__c';

        Mass_Action_Configuration__c config = new Mass_Action_Configuration__c(
            Name = 'Test Config',
            DeveloperName__c = 'Test_Config',
            Named_Credential__c = 'Mass_Action_Test_Named_Credential',
            Active__c = true,
            Batch_Size__c = 200,
            Source_Type__c = 'SOQL',
            Source_SOQL_Query__c = 'SELECT Id, Name FROM Account LIMIT 10',
            Target_Type__c = targetType,
            Target_Action_Name__c = targetActionName,
            Target_SObject_Type__c = targetSobjectType
        );

        insert config;

        Mass_Action_Mapping__c configFieldMapping = new Mass_Action_Mapping__c(
            Mass_Action_Configuration__c = config.Id,
            Source_Field_Name__c = 'Id',
            Target_Field_Name__c = 'ContextId'
        );

        insert configFieldMapping;

        Account acct = new Account(
            Name = 'Test Account'
        );

        insert acct;

        Test.setMock( HttpCalloutMock.class, new MA_HttpCalloutMock() );

        Test.startTest();

        ID jobId = Database.executeBatch( new MA_SoqlSourceBatchable( config.Id ), config.Batch_Size__c.intValue() );

        Test.stopTest();

        AsyncApexJob job = MA_MassActionBatchUtils.getJobById( jobId );

        config = [
            SELECT
                Id,
                Last_Run_Completed_Date__c,
                Last_Run_Completed_With_Errors__c
            FROM
                Mass_Action_Configuration__c
            WHERE
                Id = :config.Id
        ];

        System.assertEquals( 0, [ SELECT COUNT() FROM Mass_Action_Log__c WHERE Mass_Action_Configuration__c = :config.Id ] );
        System.assertEquals( job.CompletedDate, config.Last_Run_Completed_Date__c );
        System.assertEquals( false, config.Last_Run_Completed_With_Errors__c );

    }

    @IsTest
    static void test_batchable_fail() {

        String objectName = MA_MassActionUtils.NAMESPACE_API + 'Mass_Action_Configuration__c';

        Mass_Action_Configuration__c config = new Mass_Action_Configuration__c(
            Name = 'Test Config',
            DeveloperName__c = 'Test_Config',
            Named_Credential__c = 'Mass_Action_Test_Named_Credential',
            Active__c = true,
            Batch_Size__c = 200,
            Source_Type__c = 'SOQL',
            Source_SOQL_Query__c = 'SELECT Id, Name FROM Account LIMIT 10',
            Target_Type__c = 'Flow',
            Target_Action_Name__c = 'Test_Flow',
            Target_SObject_Type__c = null
        );

        insert config;

        Mass_Action_Mapping__c configFieldMapping = new Mass_Action_Mapping__c(
            Mass_Action_Configuration__c = config.Id,
            Source_Field_Name__c = 'NON_EXISTENT_FIELD',
            Target_Field_Name__c = 'ContextId'
        );

        insert configFieldMapping;

        Account acct = new Account(
            Name = 'Test Account'
        );

        insert acct;

        Test.setMock( HttpCalloutMock.class, new MA_HttpCalloutMock() );

        Test.startTest();

        ID jobId = Database.executeBatch( new MA_SoqlSourceBatchable( config.Id ), config.Batch_Size__c.intValue() );

        Test.stopTest();

        AsyncApexJob job = MA_MassActionBatchUtils.getJobById( jobId );

        config = [
            SELECT
                Id,
                Last_Run_Completed_Date__c,
                Last_Run_Completed_With_Errors__c
            FROM
                Mass_Action_Configuration__c
            WHERE
                Id = :config.Id
        ];

        System.assertEquals( 1, [ SELECT COUNT() FROM Mass_Action_Log__c WHERE Mass_Action_Configuration__c = :config.Id ] );
        System.assertEquals( job.CompletedDate, config.Last_Run_Completed_Date__c );
        System.assertEquals( true, config.Last_Run_Completed_With_Errors__c );

    }

}
/*
BSD 3-Clause License

Copyright (c) 2018, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/