force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Cron__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Cron__c</fullName>
    <description>Schedule Cron Expression https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Specify your own cron expression to schedule this action. See &quot;Apex Scheduler&quot; in the Salesforce Apex Developer Guide for full details on supported format.</inlineHelpText>
    <label>Schedule Cron</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_DayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>Schedule_DayOfMonth__c</fullName>
    <description>Day of Month component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which days of the month this action will run.</inlineHelpText>
    <label>Schedule Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_DayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>Schedule_DayOfWeek__c</fullName>
    <description>Weekday component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which days of the week this action will run.</inlineHelpText>
    <label>Schedule Weekday</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Frequency__c</fullName>
    <description>On Demand = not scheduled
Scheduled = user scheduled via simple options
Custom = user provided own cron expression</description>
    <inlineHelpText>How often will this action run?</inlineHelpText>
    <label>Schedule Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>On Demand</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_HourOfDay__c.field-meta.xml
<CustomField>
    <fullName>Schedule_HourOfDay__c</fullName>
    <description>Hour of Day component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which hours of the day this action will run. Salesforce uses the time zone of the user who schedules the job</inlineHelpText>
    <label>Schedule Hour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_MinuteOfHour__c.field-meta.xml
<CustomField>
    <fullName>Schedule_MinuteOfHour__c</fullName>
    <description>Minute component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which minutes of the hour this action will run.</inlineHelpText>
    <label>Schedule Minute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_MonthOfYear__c.field-meta.xml
<CustomField>
    <fullName>Schedule_MonthOfYear__c</fullName>
    <description>Month of Year component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which months of the year this action will run.</inlineHelpText>
    <label>Schedule Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_SecondOfMinute__c.field-meta.xml
<CustomField>
    <fullName>Schedule_SecondOfMinute__c</fullName>
    <description>Second component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which seconds of the minute this action will run.</inlineHelpText>
    <label>Schedule Second</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Job_Change_Event__e/Mass_Action_Job_Change_Event__e.object-meta.xml
<CustomObject>
    <description>As a workaround to known issue https://success.salesforce.com/issues_view?id=a1p30000000SyhIAAS, this platform event allows apex jobs (CronTrigger) to be scheduled and aborted from Apex REST execution context by moving the logic to another asynchronous execution context.</description>
    <label>Mass Action Job Change Event</label>
    <pluralLabel>Mass Action Job Change Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Job_Change_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Serialized JSON payload that conforms to the MA_JobChangeEvent apex class.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MA_MassActionConfigTriggerHandler.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers-org/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
public with sharing class MA_MassActionConfigTriggerHandler {

    public MA_MassActionConfigTriggerHandler() {}

    // -------------------------------------------------------
    // INSERT
    // -------------------------------------------------------

    public void handleBeforeInsert( List<Mass_Action_Configuration__c> newList ) {

        // no logic yet

    }

    public void handleAfterInsert( List<Mass_Action_Configuration__c> newList, Map<ID, Mass_Action_Configuration__c> newMap ) {

        List<Mass_Action_Configuration__c> configsToSchedule = new List<Mass_Action_Configuration__c>();

        for ( Mass_Action_Configuration__c newConfig : newList ) {

            if ( newConfig.Active__c && newConfig.Schedule_Frequency__c != 'Manual' ) {
                configsToSchedule.add( newConfig );
            }

        }

        if ( configsToSchedule.size() > 0 ) {
            scheduleMassActions( configsToSchedule );
        }

    }

    // -------------------------------------------------------
    // UPDATE
    // -------------------------------------------------------

    public void handleBeforeUpdate( List<Mass_Action_Configuration__c> oldList, Map<ID, Mass_Action_Configuration__c> oldMap,
                                    List<Mass_Action_Configuration__c> newList, Map<ID, Mass_Action_Configuration__c> newMap ) {

        // no logic yet

    }

    public void handleAfterUpdate( List<Mass_Action_Configuration__c> oldList, Map<ID, Mass_Action_Configuration__c> oldMap,
                                   List<Mass_Action_Configuration__c> newList, Map<ID, Mass_Action_Configuration__c> newMap ) {

        List<Mass_Action_Configuration__c> configsToReschedule = new List<Mass_Action_Configuration__c>();
        List<Mass_Action_Configuration__c> configsToUnschedule = new List<Mass_Action_Configuration__c>();

        for ( Mass_Action_Configuration__c newConfig : newList ) {

            Mass_Action_Configuration__c oldConfig = oldMap.get( newConfig.Id );

            System.debug( 'MA_MassActionConfigTriggerHandler.handleAfterUpdate: newConfig: ' + newConfig );
            System.debug( 'MA_MassActionConfigTriggerHandler.handleAfterUpdate: oldConfig: ' + oldConfig );

            if ( newConfig.Active__c && newConfig.Schedule_Frequency__c != 'Manual' ) {

                // Since Spring '15, code coverage calculations may not count multi-line statements
                // if the actual expression is never evaluated (e.g. if condition short-circuit)
                // so I can either make this one super long single statement, make multiple boolean expressions
                // that will be evaluated everytime, or create several test permutations.
                // Creating all possible test permutations probably is the "better practice" but
                // considering they are all just testing if two values don't match I think that's overkill.
                // So I'm opting for multiple boolean expressions that will always be evaluated to ensure coverage.
                // https://releasenotes.docs.salesforce.com/en-us/summer15/release-notes/rn_apex_expressions_coverage.htm
                // https://twitter.com/DouglasCAyers/status/942635375939538944

                Boolean activeChanged = ( oldConfig.Active__c != newConfig.Active__c );
                Boolean frequencyChanged = ( oldConfig.Schedule_Frequency__c != newConfig.Schedule_Frequency__c );
                Boolean cronChanged = ( oldConfig.Schedule_Cron__c != newConfig.Schedule_Cron__c );
                Boolean secondChanged = ( oldConfig.Schedule_SecondOfMinute__c != newConfig.Schedule_SecondOfMinute__c );
                Boolean minuteChanged = ( oldConfig.Schedule_MinuteOfHour__c != newConfig.Schedule_MinuteOfHour__c );
                Boolean hourChanged = ( oldConfig.Schedule_HourOfDay__c != newConfig.Schedule_HourOfDay__c );
                Boolean dayOfWeekChanged = ( oldConfig.Schedule_DayOfWeek__c != newConfig.Schedule_DayOfWeek__c );
                Boolean dayOfMonthChanged = ( oldConfig.Schedule_DayOfMonth__c != newConfig.Schedule_DayOfMonth__c );
                Boolean monthOfYearChanged = ( oldConfig.Schedule_MonthOfYear__c != newconfig.Schedule_MonthOfYear__c );

                Boolean reschedule = ( activeChanged || frequencyChanged || cronChanged || secondChanged || minuteChanged || hourChanged || dayOfWeekChanged || dayOfMonthChanged || monthOfYearChanged );

                if ( reschedule ) {
                    configsToReschedule.add( newConfig );
                }

            } else {

                configsToUnschedule.add( newConfig );

            }

        }

        if ( configsToReschedule.size() > 0 ) {
            rescheduleMassActions( configsToReschedule );
        }

        if ( configsToUnschedule.size() > 0 ) {
            unscheduleMassActions( configsToUnschedule );
        }

    }

    // -------------------------------------------------------
    // DELETE
    // -------------------------------------------------------

    public void handleBeforeDelete( List<Mass_Action_Configuration__c> oldList, Map<ID, Mass_Action_Configuration__c> oldMap ) {

        // no logic yet

    }

    public void handleAfterDelete( List<Mass_Action_Configuration__c> oldList, Map<ID, Mass_Action_Configuration__c> oldMap ) {

        unscheduleMassActions( oldList );

    }

    // -------------------------------------------------------

    private static void rescheduleMassActions( List<Mass_Action_Configuration__c> configs ) {

        System.debug( 'MA_MassActionConfigTriggerHandler.rescheduleMassActions' );

        unscheduleMassActions( configs );
        scheduleMassActions( configs );

    }

    private static void unscheduleMassActions( List<Mass_Action_Configuration__c> configs ) {

        System.debug( 'MA_MassActionConfigTriggerHandler.unscheduleMassActions' );

        // publishJobChangeEvent( configs, MA_JobChangeEvent.ScheduleOperation.UNSCHEDULE );
        MA_MassActionScheduleUtils.unscheduleMassActions( toIds( configs ) );

    }

    private static void scheduleMassActions( List<Mass_Action_Configuration__c> configs ) {

        System.debug( 'MA_MassActionConfigTriggerHandler.scheduleMassActions' );

        // publishJobChangeEvent( configs, MA_JobChangeEvent.ScheduleOperation.SCHEDULE );
        MA_MassActionScheduleUtils.scheduleMassActions( toIds( configs ) );

    }

    private static List<ID> toIds( List<SObject> records ) {
        List<ID> ids = new List<ID>();
        for ( SObject record : records ) {
            ids.add( record.Id );
        }
        return ids;
    }

    /**
     * When users save Mass Action Configurations using the MA_EditConfigCmp component,
     * it invokes our custom Apex REST endpoint via the LC_API component. Therefore, this
     * trigger handler ends up being invoked from within the execution context of Apex REST.
     *
     * Due to known issue that execution contexts started from Apex REST endpoints
     * cannot schedule or abort jobs, then our workaround is to use platform events
     * to move into another execution context.
     * https://success.salesforce.com/issues_view?id=a1p30000000SyhIAAS
     */
    /*
    private static void publishJobChangeEvent( List<Mass_Action_Configuration__c> configs, MA_JobChangeEvent.ScheduleOperation scheduleOperation ) {

        System.debug( 'MA_MassActionConfigTriggerHandler.publishJobChangeEvent' );
        System.debug( 'scheduleOperation=' + scheduleOperation );

        MA_JobChangeEvent eventPayload = new MA_JobChangeEvent();
        eventPayload.configIds = new List<ID>( new Map<ID, Mass_Action_Configuration__c>( configs ).keySet() );
        eventPayload.scheduleChangeOperation = scheduleOperation;

        EventBus.publish( new Mass_Action_Job_Change_Event__e(
            Payload__c = JSON.serialize( eventPayload )
        ));

    }
    */

}
/*
BSD 3-Clause License

Copyright (c) 2017-2020, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/