force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/Mass_Action_Log__c.object-meta.xml
<CustomObject>
    <description>Information about Mass Action batch job executions. You can safely delete these records after their related batch job has finished.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Log</label>
    <nameField>
        <displayFormat>MAL-{000000}</displayFormat>
        <label>Mass Action Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <description>Apex Batch Job ID. Since we can&#39;t have lookup fields to AsyncApexJob records, please standardize on the 15 character id, least common denominator for our use cases. SOQL WHERE filters will fail if stored value and filter value are not same length. Set as external id just so it&#39;s indexed. Don&#39;t UPSERT by this field value.</description>
    <inlineHelpText>Apex Batch Job ID. You can also monitor job status on the Apex Jobs page in Setup.</inlineHelpText>
    <label>Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Parent_Log__c.field-meta.xml
<CustomField>
    <fullName>Parent_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child logs capture details for child apex jobs that represent the executions of a batch job. A parent log captures details for the main apex job that represents the batch job as a whole.</description>
    <label>Parent Log</label>
    <referenceTo>Mass_Action_Log__c</referenceTo>
    <relationshipLabel>Related Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Parent_Log_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Parent_Log_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated only when the log record type is &quot;Parent Log&quot;, otherwise it is null. This allows us to have a filtered related list of parent logs on Mass Action Configuration page layout. https://douglascayers.com/2015/11/18/salesforce-filter-related-lists-without-code/</description>
    <inlineHelpText>Populated only when the log record type is &quot;Parent Log&quot;, otherwise it is null.</inlineHelpText>
    <label>Parent Log Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Logs</relationshipLabel>
    <relationshipName>Mass_Action_Parent_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/recordTypes/Child_Log.recordType-meta.xml
<RecordType>
    <fullName>Child_Log</fullName>
    <active>true</active>
    <description>Represents informational, success, and error messages of a batch job run for a configuration.</description>
    <label>Child Log</label>
</RecordType>

force-app/main/default/objects/Mass_Action_Log__c/recordTypes/Parent_Log.recordType-meta.xml
<RecordType>
    <fullName>Parent_Log</fullName>
    <active>true</active>
    <description>Exactly one parent log should exist per batch job id for a configuration.</description>
    <label>Parent Log</label>
</RecordType>

force-app/main/default/classes/MA_MassActionLogTriggerHandler.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers-org/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
public with sharing class MA_MassActionLogTriggerHandler {

    public MA_MassActionLogTriggerHandler() {}

    // -------------------------------------------------------
    // INSERT
    // -------------------------------------------------------

    public void handleBeforeInsert( List<Mass_Action_Log__c> newList ) {

        formatJobId( newList );
        assignParentLogConfiguration( newList );

    }

    public void handleAfterInsert( List<Mass_Action_Log__c> newList, Map<ID, Mass_Action_Log__c> newMap ) {

        // no logic yet

    }

    // -------------------------------------------------------
    // UPDATE
    // -------------------------------------------------------

    public void handleBeforeUpdate( List<Mass_Action_Log__c> oldList, Map<ID, Mass_Action_Log__c> oldMap,
                                    List<Mass_Action_Log__c> newList, Map<ID, Mass_Action_Log__c> newMap ) {

        formatJobId( newList );
        assignParentLogConfiguration( newList );

    }

    public void handleAfterUpdate( List<Mass_Action_Log__c> oldList, Map<ID, Mass_Action_Log__c> oldMap,
                                   List<Mass_Action_Log__c> newList, Map<ID, Mass_Action_Log__c> newMap ) {

        // no logic yet

    }

    // -------------------------------------------------------
    // DELETE
    // -------------------------------------------------------

    public void handleBeforeDelete( List<Mass_Action_Log__c> oldList, Map<ID, Mass_Action_Log__c> oldMap ) {

        cascadeDeleteChildLogs( oldMap.keySet() );

    }

    public void handleAfterDelete( List<Mass_Action_Log__c> oldList, Map<ID, Mass_Action_Log__c> oldMap ) {

        // no logic yet

    }

    // -------------------------------------------------------

    /**
     * Designed to be called during `before delete` trigger event.
     *
     * If this were called during `after delete` then the parent logs
     * will have been deleted and the child log's Parent_Log__c field
     * will have been blanked out and so the query will not find any
     * child logs to delete.
     */
    private static void cascadeDeleteChildLogs( Set<ID> parentLogIds ) {
        delete [
            SELECT
                Id
            FROM
                Mass_Action_Log__c
            WHERE
                Parent_Log__c IN :parentLogIds
                AND
                RecordType.DeveloperName = 'Child_Log'
            ORDER BY
                Parent_Log__c
        ];
    }

    /**
     * Designed to be called during `before insert` and `before update` trigger events.
     *
     * We don't have lookup fields to AsyncApexJob records.
     * When filtering by this field in SOQL, since it's technically a text field
     * and not an ID field, then the field value and filter value must match
     * length exactly. So standardizing on the 15 character id, least common denominator.
     */
    private static void formatJobId( List<Mass_Action_Log__c> newLogs ) {

        for ( Mass_Action_Log__c newLog : newLogs ) {

            if ( String.isNotBlank( newLog.Job_ID__c ) ) {
                newLog.Job_ID__c = newLog.Job_ID__c.left( 15 );
            }

        }

    }

    /**
     * Designed to be called during `before insert` and `before update` trigger events.
     *
     * Sets the new log's parent log configuration lookup field based on its record type.
     * This is how we implement filtered related lists on the mass action configuration page.
     * https://douglascayers.com/2015/11/18/salesforce-filter-related-lists-without-code/
     */
    private static void assignParentLogConfiguration( List<Mass_Action_Log__c> newLogs ) {

        Map<ID, RecordTypeInfo> recordTypeInfosMap = Mass_Action_Log__c.SObjectType.getDescribe().getRecordTypeInfosById();

        for ( Mass_Action_Log__c newLog : newLogs ) {

            RecordTypeInfo rt = recordTypeInfosMap.get( newLog.RecordTypeId );
            Boolean isParentLog = ( rt != null && rt.getDeveloperName() == 'Parent_Log' );
            newLog.Parent_Log_Configuration__c = ( isParentLog ? newLog.Mass_Action_Configuration__c : null );

        }

    }

}
/*
BSD 3-Clause License

Copyright (c) 2017-2020, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/