force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</description>
    <inlineHelpText>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>A unique name to reference this record by without knowing its ID. This is particularly useful when invoking a configuration on-demand from Process Builder or Flow.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique name to reference this record by without knowing its ID.</inlineHelpText>
    <label>Mass Action Configuration Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named Credential that provides authentication to Salesforce REST API when invoking target actions. This will be the context user for the record updates.</description>
    <inlineHelpText>By default, the user who schedules the mass actions is the context user for record updates. You may optionally choose a Named Credential to specify the context user instead.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_List_View_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_List_View_ID__c</fullName>
    <description>List View that provides the source records. Applicable when Source Type is List View.</description>
    <inlineHelpText>Choose a list view that identifies the records to process.</inlineHelpText>
    <label>Source List View ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>Where source records come from to perform actions on, like reports or list views.</description>
    <inlineHelpText>Where source records come from to perform actions on, like reports or list views.</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Action_Name__c</fullName>
    <description>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</description>
    <inlineHelpText>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</inlineHelpText>
    <label>Target Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_SObject_Type__c</fullName>
    <label>Target SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <description>Type of action to perform on the source records.</description>
    <inlineHelpText>Type of action to perform on the source records.</inlineHelpText>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
                <label>Process Builder &amp; Flows</label>
            </value>
            <value>
                <fullName>Workflow</fullName>
                <label>Workflow Rules</label>
            </value>
            <value>
                <fullName>QuickAction</fullName>
                <label>Quick Actions</label>
            </value>
            <value>
                <fullName>EmailAlert</fullName>
                <label>Email Alerts</label>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/Mass_Action_Mapping__c.object-meta.xml
<CustomObject>
    <description>Defines field mappings between sources and targets.</description>
    <label>Mass Action Mapping</label>
    <nameField>
        <displayFormat>MAM-{000000}</displayFormat>
        <label>Mass Action Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Mappings</relationshipLabel>
    <relationshipName>Mass_Action_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Source_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Name__c</fullName>
    <description>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</description>
    <inlineHelpText>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</inlineHelpText>
    <label>Source Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <description>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</description>
    <inlineHelpText>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</inlineHelpText>
    <label>Target Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MA_RunConfigInvocableTest.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers-org/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
@IsTest
private class MA_RunConfigInvocableTest {

    @TestSetup
    static void setup() {

        String objectName = MA_NamespaceUtils.NAMESPACE_API + 'Mass_Action_Configuration__c';
        ListView lv = [ SELECT Id, Name, DeveloperName, SobjectType FROM ListView WHERE DeveloperName = 'All' AND SobjectType = :objectName AND IsSoqlCompatible = true LIMIT 1 ];

        Mass_Action_Configuration__c config = new Mass_Action_Configuration__c(
            Name = 'Test Config',
            DeveloperName__c = 'Test_Config',
            Named_Credential__c = 'Mass_Action_Test_Named_Credential',
            Active__c = true,
            Batch_Size__c = 200,
            Source_Type__c = 'ListView',
            Source_List_View_ID__c = lv.Id,
            Target_Type__c = 'Apex',
            Target_Action_Name__c = 'Test_Apex',
            Target_SObject_Type__c = null
        );

        insert config;

        Mass_Action_Mapping__c configFieldMapping = new Mass_Action_Mapping__c(
            Mass_Action_Configuration__c = config.Id,
            Source_Field_Name__c = 'Id',
            Target_Field_Name__c = 'ContextId'
        );

        insert configFieldMapping;

    }

    @IsTest
    static void test_invocable_by_id() {

        Mass_Action_Configuration__c config = [ SELECT Id FROM Mass_Action_Configuration__c WHERE DeveloperName__c = 'Test_Config' LIMIT 1 ];

        Test.setMock( HttpCalloutMock.class, new MA_HttpCalloutMock() );

        Test.startTest();

        MA_RunConfigInvocable.Request req = new MA_RunConfigInvocable.Request();
        req.configId = config.Id;

        List<MA_RunConfigInvocable.Response> responses = MA_RunConfigInvocable.execute( new List<MA_RunConfigInvocable.Request>{ req } );

        System.assertEquals( 1, responses.size() );
        System.assertEquals( 1, [ SELECT COUNT() FROM AsyncApexJob WHERE Id = :responses[0].jobId ] );

    }

    @IsTest
    static void test_invocable_by_unique_name() {

        Test.setMock( HttpCalloutMock.class, new MA_HttpCalloutMock() );

        Test.startTest();

        MA_RunConfigInvocable.Request req = new MA_RunConfigInvocable.Request();
        req.configUniqueName = 'Test_Config';

        List<MA_RunConfigInvocable.Response> responses = MA_RunConfigInvocable.execute( new List<MA_RunConfigInvocable.Request>{ req } );

        System.assertEquals( 1, responses.size() );
        System.assertEquals( 1, [ SELECT COUNT() FROM AsyncApexJob WHERE Id = :responses[0].jobId ] );

    }

    @IsTest
    static void test_invocable_no_data_found() {

        Test.setMock( HttpCalloutMock.class, new MA_HttpCalloutMock() );

        Test.startTest();

        try {

            MA_RunConfigInvocable.execute( new List<MA_RunConfigInvocable.Request>{ new MA_RunConfigInvocable.Request() } );

            System.assert( false, 'should have failed' );

        } catch ( Exception e ) {

            System.assert( e instanceof System.NoDataFoundException, 'expected NoDataFoundException but got ' + e );

        }

        Test.stopTest();

    }

}
/*
BSD 3-Clause License

Copyright (c) 2017-2019, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/