force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/Mass_Action_Log__c.object-meta.xml
<CustomObject>
    <description>Information about Mass Action batch job executions. You can safely delete these records after their related batch job has finished.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Log</label>
    <nameField>
        <displayFormat>MAL-{000000}</displayFormat>
        <label>Mass Action Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/fields/Failed_Batches__c.field-meta.xml
<CustomField>
    <fullName>Failed_Batches__c</fullName>
    <description>Total number of batches with a failure. A batch is considered transactional, so any unhandled exceptions constitute an entire failure of the batch.</description>
    <inlineHelpText>Total number of batches with a failure. A batch is considered transactional, so any unhandled exceptions constitute an entire failure of the batch.</inlineHelpText>
    <label>Failed Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <description>Apex Batch Job ID. Since we can&#39;t have lookup fields to AsyncApexJob records, please standardize on the 15 character id, least common denominator for our use cases. SOQL WHERE filters will fail if stored value and filter value are not same length. Set as external id just so it&#39;s indexed. Don&#39;t UPSERT by this field value.</description>
    <inlineHelpText>Apex Batch Job ID. You can also monitor job status on the Apex Jobs page in Setup.</inlineHelpText>
    <label>Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>Job Scope from BatchApexErrorEvent. The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects.</description>
    <inlineHelpText>The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects.</inlineHelpText>
    <label>Job Scope</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Long_Message__c.field-meta.xml
<CustomField>
    <fullName>Long_Message__c</fullName>
    <description>The full error message, particularly if more than 255 characters.</description>
    <inlineHelpText>The full error message, particularly if more than 255 characters.</inlineHelpText>
    <label>Long Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Apex Job extended status with details about any errors.</description>
    <inlineHelpText>Apex Job extended status with details about any errors.</inlineHelpText>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Informational</fullName>
                <default>true</default>
                <label>ℹ️ Informational</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>✅ Success</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>🚫 Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Parent_Log__c.field-meta.xml
<CustomField>
    <fullName>Parent_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child logs capture details for child apex jobs that represent the executions of a batch job. A parent log captures details for the main apex job that represents the batch job as a whole.</description>
    <label>Parent Log</label>
    <referenceTo>Mass_Action_Log__c</referenceTo>
    <relationshipLabel>Related Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Processed_Batches__c.field-meta.xml
<CustomField>
    <fullName>Processed_Batches__c</fullName>
    <description>Total number of batches processed successfully. Each batch contains a set of records.</description>
    <inlineHelpText>Total number of batches processed successfully. Each batch contains a set of records.</inlineHelpText>
    <label>Processed Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <description>When the Apex Job was submitted.</description>
    <inlineHelpText>When the Apex Job was submitted.</inlineHelpText>
    <label>Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Total_Batches__c.field-meta.xml
<CustomField>
    <fullName>Total_Batches__c</fullName>
    <description>Total number of batches processed. Each batch contains a set of records.</description>
    <inlineHelpText>Total number of batches processed. Each batch contains a set of records.</inlineHelpText>
    <label>Total Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/recordTypes/Child_Log.recordType-meta.xml
<RecordType>
    <fullName>Child_Log</fullName>
    <active>true</active>
    <description>Represents informational, success, and error messages of a batch job run for a configuration.</description>
    <label>Child Log</label>
</RecordType>

force-app/main/default/objects/Mass_Action_Log__c/recordTypes/Parent_Log.recordType-meta.xml
<RecordType>
    <fullName>Parent_Log</fullName>
    <active>true</active>
    <description>Exactly one parent log should exist per batch job id for a configuration.</description>
    <label>Parent Log</label>
</RecordType>

force-app/main/default/classes/MA_BatchApexErrorEventTriggerHandler.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers-org/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
public without sharing class MA_BatchApexErrorEventTriggerHandler {

    public MA_BatchApexErrorEventTriggerHandler() {}

    // -------------------------------------------------------
    // INSERT
    // -------------------------------------------------------

    public void handleAfterInsert( List<BatchApexErrorEvent> newList, Map<ID, BatchApexErrorEvent> newMap ) {

        System.debug( 'MA_BatchApexErrorEventTriggerHandler.handleAfterInsert' );

        // We don't have lookup fields to AsyncApexJob records,
        // so standardizing on the 15 character id, least common denominator.
        // Also, must use string variable type because ID variable type
        // always coerces the assigned value back to 18 characters.

        Set<String> jobIds = new Set<String>();

        for ( BatchApexErrorEvent evt : newList ) {

            System.debug( 'MA_BatchApexErrorEventTriggerHandler.handleAfterInsert: ' + JSON.serializePretty( evt ) );

            jobIds.add( evt.AsyncApexJobId.left( 15 ) );

        }

        Map<ID, AsyncApexJob> jobsMap = new Map<ID, AsyncApexJob>([
            SELECT
                Id, ParentJobId, Status, ExtendedStatus, TotalJobItems, JobItemsProcessed, NumberOfErrors, CreatedDate
            FROM
                AsyncApexJob
            WHERE
                Id IN :jobIds
        ]);

        // It's possible that the batch error event's job id is
        // a child job of the main batch job that represents the
        // mass action configuration's execution.
        // The parent log record's job id will be a parent job id.
        // So to be able to cross-ref correctly, we need the parent job ids.
        Set<String> parentJobIds = new Set<String>();
        for ( AsyncApexJob job : jobsMap.values() ) {
            parentJobIds.add( String.valueOf( String.isNotBlank( job.ParentJobId ) ? job.ParentJobId : job.Id ).left( 15 ) );
        }

        Map<String, Mass_Action_Log__c> jobIdToParentLogMap = new Map<String, Mass_Action_Log__c>();
        for ( Mass_Action_Log__c parentLog : [
            SELECT
                Id, Job_ID__c, Mass_Action_Configuration__c
            FROM
                Mass_Action_Log__c
            WHERE
                Job_ID__c IN :parentJobIds
                AND
                RecordType.DeveloperName = 'Parent_Log'
        ]) {
            jobIdToParentLogMap.put( parentLog.Job_ID__c.left( 15 ), parentLog );
        }

        Map<String,RecordTypeInfo> logRecordTypeInfosMap = Mass_Action_Log__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName();

        List<Mass_Action_Log__c> parentLogsToUpdate = new List<Mass_Action_Log__c>();
        List<Mass_Action_Log__c> childLogsToInsert = new List<Mass_Action_Log__c>();

        for ( BatchApexErrorEvent evt : newList ) {

            AsyncApexJob job = jobsMap.get( ID.valueOf( evt.AsyncApexJobId ) );
            Mass_Action_Log__c parentLog = jobIdToParentLogMap.get( evt.AsyncApexJobId.left( 15 ) );

            // if either the job or parent log are null then
            // this batch error event is not for mass action scheduler, skip it
            if ( job != null && parentLog != null ) {

                switch on ( evt.Phase ) {

                    when 'START' {

                        parentLogsToUpdate.add( new Mass_Action_Log__c(
                            Id = parentLog.Id,
                            Message_Type__c = 'Error',
                            Message__c = 'Error in batch job phase ' + evt.Phase + ': ' + evt.Message,
                            Long_Message__c = 'Phase: ' + evt.Phase + '\nMessage: ' + evt.Message + '\nExceptionType: ' + evt.ExceptionType + '\nStackTrace: ' + evt.StackTrace,
                            Job_Scope__c = evt.JobScope,
                            Submitted_Date__c = job.CreatedDate,
                            Total_Batches__c = job.TotalJobItems,
                            Processed_Batches__c = job.JobItemsProcessed,
                            Failed_Batches__c = job.NumberOfErrors
                        ));

                    }

                    when 'EXECUTE' {

                        parentLogsToUpdate.add( new Mass_Action_Log__c(
                            Id = parentLog.Id,
                            Message_Type__c = 'Informational',
                            Message__c = 'Batch job processing',
                            Submitted_Date__c = job.CreatedDate,
                            Total_Batches__c = job.TotalJobItems,
                            Processed_Batches__c = job.JobItemsProcessed,
                            Failed_Batches__c = job.NumberOfErrors
                        ));

                        childLogsToInsert.add( new Mass_Action_Log__c(
                            RecordTypeId = logRecordTypeInfosMap.get( 'Child_Log' ).getRecordTypeId(),
                            Mass_Action_Configuration__c = parentLog.Mass_Action_Configuration__c,
                            Parent_Log__c = parentLog.Id,
                            Job_ID__c = parentLog.Job_ID__c,
                            Message_Type__c = 'Error',
                            Message__c = 'Error in batch job phase ' + evt.Phase + ': ' + evt.Message,
                            Long_Message__c = 'Phase: ' + evt.Phase + '\nMessage: ' + evt.Message + '\nExceptionType: ' + evt.ExceptionType + '\nStackTrace: ' + evt.StackTrace,
                            Job_Scope__c = evt.JobScope
                        ));

                    }

                    WHEN 'FINISH' {

                        parentLogsToUpdate.add( new Mass_Action_Log__c(
                            Id = parentLog.Id,
                            Message_Type__c = 'Error',
                            Message__c = 'Error in batch job phase ' + evt.Phase + ': ' + evt.Message,
                            Long_Message__c = 'Phase: ' + evt.Phase + '\nMessage: ' + evt.Message + '\nExceptionType: ' + evt.ExceptionType + '\nStackTrace: ' + evt.StackTrace,
                            Job_Scope__c = evt.JobScope,
                            Submitted_Date__c = job.CreatedDate,
                            Total_Batches__c = job.TotalJobItems,
                            Processed_Batches__c = job.JobItemsProcessed,
                            Failed_Batches__c = job.NumberOfErrors
                        ));

                    }

                }

            }

        }

        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.allowFieldTruncation = true;

        Database.insert( childLogsToInsert, dmo );
        Database.update( parentLogsToUpdate, dmo );

    }

}
/*
BSD 3-Clause License

Copyright (c) 2017-2019, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/