force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</description>
    <inlineHelpText>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Last_Run_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Completed_Date__c</fullName>
    <description>When the last run of this configuration completed. It is updated when the batch job finishes. Use this field to control when you chain other configurations together. For example, Process Builder may monitor when this field value changes and if the unique name is "Config1" then can decide to automatically run "Config2" to ensure "Config2" only runs after "Config1" completes.</description>
    <inlineHelpText>When the last run of this configuration completed. It is updated when the batch job finishes. Use this field to control when you chain other configurations together. For example, to ensure "Config2" only runs after "Config1" completes.</inlineHelpText>
    <label>Last Run Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Last_Run_Completed_With_Errors__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Completed_With_Errors__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the last run of this configuration completed with errors. It is updated when the batch job finishes. This field is checked if the last run of this configuration created log records reporting any errors, otherwise it is unchecked. Use this field with the Last Run Completed Date in Process Builder to control when to automatically run other configurations conditionally upon a configuration completing successfully or not. For example, run &quot;Config2&quot; only if &quot;Config1&quot; completed without errors.</description>
    <inlineHelpText>Indicates if the last run of this configuration completed with errors. It is updated when the batch job finishes. This field is checked if the last run of this configuration created log records reporting any errors, otherwise it is unchecked.</inlineHelpText>
    <label>Last Run Completed With Errors</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>Where source records come from to perform actions on, like reports or list views.</description>
    <inlineHelpText>Where source records come from to perform actions on, like reports or list views.</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/Mass_Action_Log__c.object-meta.xml
<CustomObject>
    <description>Information about Mass Action batch job executions. You can safely delete these records after their related batch job has finished.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Log</label>
    <nameField>
        <displayFormat>MAL-{000000}</displayFormat>
        <label>Mass Action Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Log__c/fields/Failed_Batches__c.field-meta.xml
<CustomField>
    <fullName>Failed_Batches__c</fullName>
    <description>Total number of batches with a failure. A batch is considered transactional, so any unhandled exceptions constitute an entire failure of the batch.</description>
    <inlineHelpText>Total number of batches with a failure. A batch is considered transactional, so any unhandled exceptions constitute an entire failure of the batch.</inlineHelpText>
    <label>Failed Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <description>Apex Batch Job ID. Since we can&#39;t have lookup fields to AsyncApexJob records, please standardize on the 15 character id, least common denominator for our use cases. SOQL WHERE filters will fail if stored value and filter value are not same length. Set as external id just so it&#39;s indexed. Don&#39;t UPSERT by this field value.</description>
    <inlineHelpText>Apex Batch Job ID. You can also monitor job status on the Apex Jobs page in Setup.</inlineHelpText>
    <label>Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Long_Message__c.field-meta.xml
<CustomField>
    <fullName>Long_Message__c</fullName>
    <description>The full error message, particularly if more than 255 characters.</description>
    <inlineHelpText>The full error message, particularly if more than 255 characters.</inlineHelpText>
    <label>Long Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Logs</relationshipLabel>
    <relationshipName>Mass_Action_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Apex Job extended status with details about any errors.</description>
    <inlineHelpText>Apex Job extended status with details about any errors.</inlineHelpText>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Processed_Batches__c.field-meta.xml
<CustomField>
    <fullName>Processed_Batches__c</fullName>
    <description>Total number of batches processed successfully. Each batch contains a set of records.</description>
    <inlineHelpText>Total number of batches processed successfully. Each batch contains a set of records.</inlineHelpText>
    <label>Processed Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <description>When the Apex Job was submitted.</description>
    <inlineHelpText>When the Apex Job was submitted.</inlineHelpText>
    <label>Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Log__c/fields/Total_Batches__c.field-meta.xml
<CustomField>
    <fullName>Total_Batches__c</fullName>
    <description>Total number of batches processed. Each batch contains a set of records.</description>
    <inlineHelpText>Total number of batches processed. Each batch contains a set of records.</inlineHelpText>
    <label>Total Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MA_MassActionBatchUtils.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
public inherited sharing class MA_MassActionBatchUtils {

    public static ID enqueueAction( ID configId ) {

        Mass_Action_Configuration__c config = MA_MassActionUtils.getConfiguration( configId );

        System.debug( 'MA_MassActionBatchUtils.enqueueAction: ' + config );

        ID jobId = null;

        if ( config.Active__c ) {

            if ( config.Source_Type__c == 'Report' ) {

                jobId = enqueueReportJob( config );

            } else if ( config.Source_Type__c == 'ListView' ) {

                jobId = enqueueListViewJob( config );

            } else if ( config.Source_Type__c == 'SOQL' ) {

                jobId = enqueueSoqlJob( config );

            } else {

                throw new MA_Exceptions.UnsupportedSourceTypeException( configId, config.Source_Type__c );

            }

        } else {

            System.debug( LoggingLevel.WARN, 'Not enqueueing inactive configuration' );

        }

        System.debug( 'jobId: ' + jobId );

        return jobId;
    }

    private static ID enqueueReportJob( Mass_Action_Configuration__c config ) {

        return Database.executeBatch( new MA_ReportSourceBatchable( config.Id ), config.Batch_Size__c.intValue() );
    }

    private static ID enqueueListViewJob( Mass_Action_Configuration__c config ) {

        return Database.executeBatch( new MA_ListViewSourceBatchable( config.Id ), config.Batch_Size__c.intValue() );
    }

    private static ID enqueueSoqlJob( Mass_Action_Configuration__c config ) {

        return Database.executeBatch( new MA_SoqlSourceBatchable( config.Id ), config.Batch_Size__c.intValue() );
    }

    // ----------------------------------------------------

    /**
     * Designed to be invoked during the batch finish method.
     */
    public static void handleBatchJobFinished( ID configId, ID jobId ) {

        System.debug( 'MA_MassActionBatchUtils.handleBatchJobFinished: configId=' + configId + ', jobId=' + jobId );

        // we don't have lookup fields to AsyncApexJob records
        // so standardizing on the 15 character id, least common denominator
        // also, must use string variable type because ID variable type
        // always coerces the assigned value back to 18 characters
        String jobId15 = String.valueOf( jobId ).left( 15 );

        AsyncApexJob job = getJobById( jobId );

        // this may or may not insert a job error log record,
        // so run first before querying for count of error logs
        logJobErrors( configId, job, null );

        // if actual batch job didn't fail with an error,
        // check if any of the batch executions logged errors
        Integer jobErrorCount = [
            SELECT
                COUNT()
            FROM
                Mass_Action_Log__c
            WHERE
                Mass_Action_Configuration__c = :configId
                AND
                Job_ID__c = :jobId15
        ];

        Mass_Action_Configuration__c config = new Mass_Action_Configuration__c(
            Id = configId,
            Last_Run_Completed_Date__c = job.CompletedDate,
            Last_Run_Completed_With_Errors__c = ( jobErrorCount > 0 )
        );

        update config;

    }

    // ----------------------------------------------------

    /**
     * Designed to be invoked when an exception is caught during a batch execution.
     * Exceptions are caught so that one batch execution doesn't halt the entire job.
     */
    public static void logJobException( ID configId, ID jobId, Exception ex ) {

        System.debug( 'MA_MassActionBatchUtils.logJobException: configId=' + configId + ', jobId=' + jobId );
        logJobErrors( configId, getJobById( jobId ), ex );

    }

    // ----------------------------------------------------

    /**
     * Analyzes the job results and will create a Mass_Action_Log__c if job failed, or exception argument is not null.
     */
    @TestVisible
    private static void logJobErrors( ID configId, AsyncApexJob job, Exception ex ) {

        System.debug( 'MA_MassActionBatchUtils.logJobErrors: configId=' + configId + ', job=' + job + ', exception=' + ex );

        // we don't have lookup fields to AsyncApexJob records
        // so standardizing on the 15 character id, least common denominator
        // also, must use string variable type because ID variable type
        // always coerces the assigned value back to 18 characters
        String jobId15 = String.valueOf( job.Id ).left( 15 );

        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.allowFieldTruncation = true;

        if ( String.isNotBlank( job.ExtendedStatus ) || ( ex != null ) ) {

            // default the job error to short message as its only 255 chars
            // and put exception in long message
            String shortMessage = ( String.isBlank( job.ExtendedStatus ) ? null : job.ExtendedStatus );
            String longMessage = ( ex == null ? null : ex.getMessage() );

            // if either message field is blank then copy the other into it
            // because our DML option truncates values then its ok to copy long message into short
            shortMessage = ( String.isBlank( shortMessage ) ? longMessage : shortMessage );
            longMessage = ( String.isBlank( longMessage ) ? shortMessage : longMessage );

            Mass_Action_Log__c log = new Mass_Action_Log__c(
                Mass_Action_Configuration__c = configId,
                Job_ID__c = jobId15,
                Submitted_Date__c = job.CreatedDate,
                Total_Batches__c = job.TotalJobItems,
                Processed_Batches__c = job.JobItemsProcessed,
                Failed_Batches__c = job.NumberOfErrors,
                Message__c = shortMessage,
                Long_Message__c = longMessage
            );

            Database.insert( log, dmo );

            System.debug( log );

        }

    }

    // ----------------------------------------------------

    public static AsyncApexJob getJobById( ID jobId ) {
        return [
            SELECT
                Id,
                CreatedDate,
                CompletedDate,
                ExtendedStatus,
                TotalJobItems,
                JobItemsProcessed,
                NumberOfErrors
            FROM
                AsyncApexJob
            WHERE
                Id = :jobId
        ];
    }

}
/*
BSD 3-Clause License

Copyright (c) 2018, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/