force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</description>
    <inlineHelpText>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>A unique name to reference this record by without knowing its ID. This is particularly useful when invoking a configuration on-demand from Process Builder or Flow.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique name to reference this record by without knowing its ID.</inlineHelpText>
    <label>Mass Action Configuration Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named Credential that provides authentication to Salesforce REST API when invoking target actions. This will be the context user for the record updates.</description>
    <inlineHelpText>By default, the user who schedules the mass actions is the context user for record updates. You may optionally choose a Named Credential to specify the context user instead.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Cron__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Cron__c</fullName>
    <description>Schedule Cron Expression https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Specify your own cron expression to schedule this action. See &quot;Apex Scheduler&quot; in the Salesforce Apex Developer Guide for full details on supported format.</inlineHelpText>
    <label>Schedule Cron</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_DayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>Schedule_DayOfMonth__c</fullName>
    <description>Day of Month component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which days of the month this action will run.</inlineHelpText>
    <label>Schedule Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Frequency__c</fullName>
    <description>On Demand = not scheduled
Scheduled = user scheduled via simple options
Custom = user provided own cron expression</description>
    <inlineHelpText>How often will this action run?</inlineHelpText>
    <label>Schedule Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>On Demand</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_HourOfDay__c.field-meta.xml
<CustomField>
    <fullName>Schedule_HourOfDay__c</fullName>
    <description>Hour of Day component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which hours of the day this action will run. Salesforce uses the time zone of the user who schedules the job</inlineHelpText>
    <label>Schedule Hour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_MinuteOfHour__c.field-meta.xml
<CustomField>
    <fullName>Schedule_MinuteOfHour__c</fullName>
    <description>Minute component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which minutes of the hour this action will run.</inlineHelpText>
    <label>Schedule Minute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_SecondOfMinute__c.field-meta.xml
<CustomField>
    <fullName>Schedule_SecondOfMinute__c</fullName>
    <description>Second component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which seconds of the minute this action will run.</inlineHelpText>
    <label>Schedule Second</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Source_Apex_Class__c</fullName>
    <description>Name (including namespace if applicable) of an Apex class that implements Iterable&lt;Map&lt;String, Object&gt;&gt;. The returned iterator produces the source records to process. This also is a way, other than External Objects, to process data retrieved from HTTP callouts to external web services. You could query an external system to learn the Salesforce record IDs to apply updates to.</description>
    <inlineHelpText>Name (including namespace if applicable) of an Apex class that implements Iterable&lt;Map&lt;String, Object&gt;&gt;. The returned iterator produces the source records to process. The source data, for example, could come from HTTP callouts to external web services.</inlineHelpText>
    <label>Source Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_List_View_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_List_View_ID__c</fullName>
    <description>List View that provides the source records. Applicable when Source Type is List View.</description>
    <inlineHelpText>Choose a list view that identifies the records to process.</inlineHelpText>
    <label>Source List View ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Report_Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Report_Column_Name__c</fullName>
    <description>Report column name that holds unique record values for sorting and paginating. Needed for workaround with Reports API to process more than 2,000 rows. Applicable when Source Type is Report.</description>
    <inlineHelpText>Report column name that holds unique record values for sorting and paginating. Needed for workaround with Reports API to process more than 2,000 rows. Applicable when Source Type is Report.</inlineHelpText>
    <label>Source Report Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_Report_ID__c</fullName>
    <description>Report that provides the source records. Applicable when Source Type is Report.</description>
    <inlineHelpText>Report that provides the source records. Applicable when Source Type is Report.</inlineHelpText>
    <label>Source Report ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_SOQL_Query__c.field-meta.xml
<CustomField>
    <fullName>Source_SOQL_Query__c</fullName>
    <description>SOQL query that provides the source records. Applicable when Source Type is SOQL. Max SOQL query length limit: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm</description>
    <inlineHelpText>Enter SOQL query that identifies the records to process. Use aliases with Aggregate functions (COUNT, SUM, MIN, MAX, AVG, etc.) to make them available in the Field Mappings step.</inlineHelpText>
    <label>Source SOQL Query</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>Where source records come from to perform actions on, like reports or list views.</description>
    <inlineHelpText>Where source records come from to perform actions on, like reports or list views.</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Action_Name__c</fullName>
    <description>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</description>
    <inlineHelpText>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</inlineHelpText>
    <label>Target Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Apex_Script__c.field-meta.xml
<CustomField>
    <fullName>Target_Apex_Script__c</fullName>
    <description>Anonymous Apex script to execute. Your script must include a method definition for `void execute( List&lt;Map&lt;String, Object&gt;&gt; sourceRecordsBatch )`, which will be passed the current batch of source records. Your script is invoked once per batch just like the `execute` method of a Batchable class. Unlike a Batchable class, no state is preserved within the script between executions.</description>
    <inlineHelpText>Anonymous Apex script to execute. Your script must include a method definition for `void execute( List&lt;Map&lt;String, Object&gt;&gt; sourceRecordsBatch )`, which will be passed the current batch of source records. No script state is preserved between executions.</inlineHelpText>
    <label>Target Apex Script</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_SObject_Type__c</fullName>
    <label>Target SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <description>Type of action to perform on the source records.</description>
    <inlineHelpText>Type of action to perform on the source records.</inlineHelpText>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
                <label>Process Builder &amp; Flows</label>
            </value>
            <value>
                <fullName>Workflow</fullName>
                <label>Workflow Rules</label>
            </value>
            <value>
                <fullName>QuickAction</fullName>
                <label>Quick Actions</label>
            </value>
            <value>
                <fullName>EmailAlert</fullName>
                <label>Email Alerts</label>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/Mass_Action_Mapping__c.object-meta.xml
<CustomObject>
    <description>Defines field mappings between sources and targets.</description>
    <label>Mass Action Mapping</label>
    <nameField>
        <displayFormat>MAM-{000000}</displayFormat>
        <label>Mass Action Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Mappings</relationshipLabel>
    <relationshipName>Mass_Action_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MA_MassActionConfigWrapper.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers-org/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
/*
 * To simplify efforts to have one code base that can be open source
 * and in a managed package, and the code not have to know about any
 * namespace then rather than serialize custom sobjects or fields to
 * our Lightning Components we instead have an abstraction layer.
 *
 * Regardless the namespace of the org the code is deployed into,
 * the Lightning Compnent javascript can always reference attributes
 * from this class without worry.
 *
 * Test code coverage provided by MA_EditConfigCmpControllerTest.
 */
public inherited sharing class MA_MassActionConfigWrapper {

    @AuraEnabled
    public ID recordId { get; set; }

    @AuraEnabled
    public ID ownerId { get; set; }

    @AuraEnabled
    public String name { get; set; }

    @AuraEnabled
    public String developerName { get; set; }

    @AuraEnabled
    public String namedCredential { get; set; }

    @AuraEnabled
    public Boolean active { get; set; }

    @AuraEnabled
    public Integer batchSize { get; set; }

    @AuraEnabled
    public String description { get; set; }

    // source

    @AuraEnabled
    public String sourceType { get; set; }

    @AuraEnabled
    public String sourceReportID { get; set; }

    @AuraEnabled
    public String sourceReportColumnName { get; set; }

    @AuraEnabled
    public String sourceListViewID { get; set; }

    @AuraEnabled
    public String sourceSoqlQuery { get; set; }

    @AuraEnabled
    public String sourceApexClass { get; set; }

    // target

    @AuraEnabled
    public String targetType { get; set; }

    @AuraEnabled
    public String targetSobjectType { get; set; }

    @AuraEnabled
    public String targetActionName { get; set; }

    @AuraEnabled
    public String targetApexScript { get; set; }

    // schedule

    @AuraEnabled
    public String scheduleFrequency { get; set; }

    @AuraEnabled
    public String scheduleCron { get; set; }

    @AuraEnabled
    public String scheduleSecondOfMinute { get; set; }

    @AuraEnabled
    public String scheduleMinuteOfHour { get; set; }

    @AuraEnabled
    public String scheduleHourOfDay { get; set; }

    @AuraEnabled
    public String scheduleDayOfMonth { get; set; }

    @AuraEnabled
    public String scheduleMonthOfYear { get; set; }

    @AuraEnabled
    public String scheduleDayOfWeek { get; set; }

    // system

    @AuraEnabled
    public ID createdById { get; set; }

    @AuraEnabled
    public DateTime createdDate { get; set; }

    @AuraEnabled
    public ID lastModifiedById { get; set; }

    @AuraEnabled
    public DateTime lastModifiedDate { get; set; }

    @AuraEnabled
    public List<FieldMappingWrapper> fieldMappings { get; set; }

    public MA_MassActionConfigWrapper() { }

    public MA_MassActionConfigWrapper( Mass_Action_Configuration__c config ) {

        this.fieldMappings = new List<FieldMappingWrapper>();

        // defaults
        this.active = true;
        this.batchSize = 200;

        if ( config != null ) {

            this.recordId = config.Id;
            this.ownerId = config.OwnerId;
            this.name = config.Name;
            this.developerName = config.DeveloperName__c;
            this.namedCredential = config.Named_Credential__c;
            this.active = ( config.Active__c == null ? this.active : config.Active__c );
            this.batchSize = ( config.Batch_Size__c == null ? this.batchSize : config.Batch_Size__c.intValue() );
            this.description = config.Description__c;
            // source
            this.sourceType = config.Source_Type__c;
            this.sourceReportID = config.Source_Report_ID__c;
            this.sourceReportColumnName = config.Source_Report_Column_Name__c;
            this.sourceListViewID = config.Source_List_View_ID__c;
            this.sourceSoqlQuery = config.Source_SOQL_Query__c;
            this.sourceApexClass = config.Source_Apex_Class__c;
            // target
            this.targetType = config.Target_Type__c;
            this.targetSobjectType = config.Target_SObject_Type__c;
            this.targetActionName = config.Target_Action_Name__c;
            this.targetApexScript = config.Target_Apex_Script__c;
            // schedule
            this.scheduleFrequency = config.Schedule_Frequency__c;
            this.scheduleCron = config.Schedule_Cron__c;
            this.scheduleSecondOfMinute = config.Schedule_SecondOfMinute__c;
            this.scheduleMinuteOfHour = config.Schedule_MinuteOfHour__c;
            this.scheduleHourOfDay = config.Schedule_HourOfDay__c;
            this.scheduleDayOfMonth = config.Schedule_DayOfMonth__c;
            this.scheduleMonthOfYear = config.Schedule_MonthOfYear__c;
            this.scheduleDayOfWeek = config.Schedule_DayOfWeek__c;
            // system
            this.createdById = config.CreatedById;
            this.createdDate = config.CreatedDate;
            this.lastModifiedById = config.LastModifiedById;
            this.lastModifiedDate = config.LastModifiedDate;

            for ( Mass_Action_Mapping__c mapping : config.Mass_Action_Mappings__r ) {
                this.fieldMappings.add( new FieldMappingWrapper( mapping ) );
            }

        }

    }

    public Mass_Action_Configuration__c toConfiguration() {

        Mass_Action_Configuration__c config = new Mass_Action_Configuration__c(
            Name = this.name,
            DeveloperName__c = this.developerName,
            Named_Credential__c = this.namedCredential,
            Active__c = ( this.active == null ? true : this.active ),
            Batch_Size__c = ( this.batchSize == null ? 200 : this.batchSize ),
            Description__c = this.description,
            // source
            Source_Type__c = this.sourceType,
            Source_Report_ID__c = this.sourceReportID,
            Source_Report_Column_Name__c = this.sourceReportColumnName,
            Source_List_View_ID__c = this.sourceListViewID,
            Source_SOQL_Query__c = this.sourceSoqlQuery,
            Source_Apex_Class__c = this.sourceApexClass,
            // target
            Target_Type__c = this.targetType,
            Target_SObject_Type__c = this.targetSobjectType,
            Target_Action_Name__c = this.targetActionName,
            Target_Apex_Script__c = this.targetApexScript,
            // schedule
            Schedule_Frequency__c = this.scheduleFrequency,
            Schedule_Cron__c = this.scheduleCron,
            Schedule_SecondOfMinute__c = this.scheduleSecondOfMinute,
            Schedule_MinuteOfHour__c = this.scheduleMinuteOfHour,
            Schedule_HourOfDay__c = this.scheduleHourOfDay,
            Schedule_DayOfMonth__c = this.scheduleDayOfMonth,
            Schedule_MonthOfYear__c = this.scheduleMonthOfYear,
            Schedule_DayOfWeek__c = this.scheduleDayOfWeek
        );

        // some fields need to not be "set" otherwise will cause errors if set to null
        // so only if there are actual values to assign then we leave these unset
        if ( String.isNotBlank( this.recordId ) ) {
            config.Id = this.recordId;
        }

        if ( String.isNotBlank( this.ownerId ) ) {
            config.OwnerId = this.ownerId;
        }

        return config;
    }

    public inherited sharing class FieldMappingWrapper {

        @AuraEnabled
        public String sourceFieldName { get; set; }

        @AuraEnabled
        public String targetFieldName { get; set; }

        public FieldMappingWrapper( Mass_Action_Mapping__c mapping ) {
            this.sourceFieldName = mapping.Source_Field_Name__c;
            this.targetFieldName = mapping.Target_Field_Name__c;
        }

    }

}
/*
BSD 3-Clause License

Copyright (c) 2017-2020, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/