force-app/main/default/objects/Mass_Action_Configuration__c/Mass_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>A configuration of inputs (reports, list views, queries) and actions (process builder, flows, apex) that can be scheduled.
https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/</description>
    <label>Mass Action Configuration</label>
    <nameField>
        <label>Mass Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</description>
    <inlineHelpText>If active then action can be ran and scheduled. Inactive actions will not run and have their scheduled job aborted.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</description>
    <inlineHelpText>The number of source records to run through the target action at a time. Correlates to the apex batch job size. Can be between 1 and 200. Same concept as Data Loader&#39;s batch size.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>A unique name to reference this record by without knowing its ID. This is particularly useful when invoking a configuration on-demand from Process Builder or Flow.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique name to reference this record by without knowing its ID.</inlineHelpText>
    <label>Mass Action Configuration Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named Credential that provides authentication to Salesforce REST API when invoking target actions. This will be the context user for the record updates.</description>
    <inlineHelpText>By default, the user who schedules the mass actions is the context user for record updates. You may optionally choose a Named Credential to specify the context user instead.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Cron__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Cron__c</fullName>
    <description>Schedule Cron Expression https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Specify your own cron expression to schedule this action. See &quot;Apex Scheduler&quot; in the Salesforce Apex Developer Guide for full details on supported format.</inlineHelpText>
    <label>Schedule Cron</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_DayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>Schedule_DayOfMonth__c</fullName>
    <description>Day of Month component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which days of the month this action will run.</inlineHelpText>
    <label>Schedule Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_DayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>Schedule_DayOfWeek__c</fullName>
    <description>Weekday component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which days of the week this action will run.</inlineHelpText>
    <label>Schedule Weekday</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Frequency__c</fullName>
    <description>On Demand = not scheduled
Scheduled = user scheduled via simple options
Custom = user provided own cron expression</description>
    <inlineHelpText>How often will this action run?</inlineHelpText>
    <label>Schedule Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>On Demand</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_HourOfDay__c.field-meta.xml
<CustomField>
    <fullName>Schedule_HourOfDay__c</fullName>
    <description>Hour of Day component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which hours of the day this action will run. Salesforce uses the time zone of the user who schedules the job</inlineHelpText>
    <label>Schedule Hour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_MinuteOfHour__c.field-meta.xml
<CustomField>
    <fullName>Schedule_MinuteOfHour__c</fullName>
    <description>Minute component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which minutes of the hour this action will run.</inlineHelpText>
    <label>Schedule Minute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_MonthOfYear__c.field-meta.xml
<CustomField>
    <fullName>Schedule_MonthOfYear__c</fullName>
    <description>Month of Year component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which months of the year this action will run.</inlineHelpText>
    <label>Schedule Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Schedule_SecondOfMinute__c.field-meta.xml
<CustomField>
    <fullName>Schedule_SecondOfMinute__c</fullName>
    <description>Second component of cron schedule expression. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</description>
    <inlineHelpText>Choose which seconds of the minute this action will run.</inlineHelpText>
    <label>Schedule Second</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_List_View_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_List_View_ID__c</fullName>
    <description>List View that provides the source records. Applicable when Source Type is List View.</description>
    <inlineHelpText>Choose a list view that identifies the records to process.</inlineHelpText>
    <label>Source List View ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Report_Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Report_Column_Name__c</fullName>
    <description>Report column name that holds unique record values for sorting and paginating. Needed for workaround with Reports API to process more than 2,000 rows. Applicable when Source Type is Report.</description>
    <inlineHelpText>Report column name that holds unique record values for sorting and paginating. Needed for workaround with Reports API to process more than 2,000 rows. Applicable when Source Type is Report.</inlineHelpText>
    <label>Source Report Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_Report_ID__c</fullName>
    <description>Report that provides the source records. Applicable when Source Type is Report.</description>
    <inlineHelpText>Report that provides the source records. Applicable when Source Type is Report.</inlineHelpText>
    <label>Source Report ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>Where source records come from to perform actions on, like reports or list views.</description>
    <inlineHelpText>Where source records come from to perform actions on, like reports or list views.</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Action_Name__c</fullName>
    <description>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</description>
    <inlineHelpText>Name of the action to process the source records (e.g. Process Builder, Flow, Invocable Apex class, Quick Action, Email Alert, etc). Should be blank for when Target Type is Workflow Rules.</inlineHelpText>
    <label>Target Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_SObject_Type__c</fullName>
    <label>Target SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Configuration__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <description>Type of action to perform on the source records.</description>
    <inlineHelpText>Type of action to perform on the source records.</inlineHelpText>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
                <label>Process Builder &amp; Flows</label>
            </value>
            <value>
                <fullName>Workflow</fullName>
                <label>Workflow Rules</label>
            </value>
            <value>
                <fullName>QuickAction</fullName>
                <label>Quick Actions</label>
            </value>
            <value>
                <fullName>EmailAlert</fullName>
                <label>Email Alerts</label>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/Mass_Action_Mapping__c.object-meta.xml
<CustomObject>
    <description>Defines field mappings between sources and targets.</description>
    <label>Mass Action Mapping</label>
    <nameField>
        <displayFormat>MAM-{000000}</displayFormat>
        <label>Mass Action Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Action Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Mass_Action_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Mass_Action_Configuration__c</fullName>
    <label>Mass Action Configuration</label>
    <referenceTo>Mass_Action_Configuration__c</referenceTo>
    <relationshipLabel>Mass Action Mappings</relationshipLabel>
    <relationshipName>Mass_Action_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Source_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Name__c</fullName>
    <description>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</description>
    <inlineHelpText>API name of the source record to map to the target field. For example, the unique column name in a report or list view.</inlineHelpText>
    <label>Source Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Action_Mapping__c/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <description>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</description>
    <inlineHelpText>API name of the target parameter to map to the source field. For example, the parameter name to a Flow.</inlineHelpText>
    <label>Target Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MA_MassActionUtils.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers/sfdx-mass-action-scheduler
 * License: BSD 3-Clause License
 */
/*
 * Most code coverage comes from MA_EditConfigCmpControllerTest
 */
public with sharing class MA_MassActionUtils {

    // -- private --

    private static final String MY_NAMESPACE = [ SELECT NamespacePrefix FROM ApexClass WHERE Name = 'MA_MassActionUtils' LIMIT 1 ].NamespacePrefix;

    // -- public --

    public static final String NAMESPACE = String.isBlank( MY_NAMESPACE ) ? '' : MY_NAMESPACE;
    public static final String NAMESPACE_API = String.isBlank( MY_NAMESPACE ) ? '' : MY_NAMESPACE + '__';

    public static final String EMPTY_STRING = '';

    public static final String REST_API_SERVICES_DATA_URL = Url.getOrgDomainUrl().toExternalForm() + '/services/data/v44.0';

    // ------------------------------------------------------------------------

    /**
     * Queries the config record and its related field mappings.
     * Returns null if no record is found.
     */
    public static Mass_Action_Configuration__c getConfiguration( ID recordId ) {

        Mass_Action_Configuration__c config = null;

        for ( Mass_Action_Configuration__c record : [
            SELECT
                Id,
                OwnerId,
                Name,
                DeveloperName__c,
                Named_Credential__c,
                Active__c,
                Batch_Size__c,
                Description__c,
                // source
                Source_Type__c,
                Source_Report_ID__c,
                Source_Report_Column_Name__c,
                Source_List_View_ID__c,
                // target
                Target_Type__c,
                Target_SObject_Type__c,
                Target_Action_Name__c,
                // schedule
                Schedule_Frequency__c,
                Schedule_Cron__c,
                Schedule_SecondOfMinute__c,
                Schedule_MinuteOfHour__c,
                Schedule_HourOfDay__c,
                Schedule_DayOfMonth__c,
                Schedule_MonthOfYear__c,
                Schedule_DayOfWeek__c,
                // system
                CreatedById,
                CreatedDate,
                LastModifiedById,
                LastModifiedDate,
                // mappings
                (
                    SELECT
                        Id,
                        Source_Field_Name__c,
                        Target_Field_Name__c
                    FROM
                        Mass_Action_Mappings__r
                    FOR REFERENCE
                )
            FROM
                Mass_Action_Configuration__c
            WHERE
                Id = :recordId
            FOR VIEW
        ]) {
            config = record;
        }

        return config;
    }

    /**
     * The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     * or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     */
    public static MA_ListViewDescribeResult describeListView( String baseURL, ID listViewId ) {

        ListView listView = [ SELECT id, sobjectType FROM ListView WHERE id = :listViewId LIMIT 1 ];

        String endpoint = String.format(
            '{0}/sobjects/{1}/listviews/{2}/describe',
            new String[] { baseURL, listView.sobjectType, listView.id }
        );

        HttpRequest req = new HttpRequest();
        req.setEndpoint( endpoint );
        req.setMethod( 'GET' );
        req.setTimeout( 120000 ); // max wait of 2 mins
        req.setCompressed( true );
        req.setHeader( 'Content-Type', 'application/json' );
        req.setHeader( 'Accepts', 'application/json' );
        req.setHeader( 'Authorization', 'Bearer ' + UserInfo.getSessionId() );

        HttpResponse res = sendHttpRequest( req );

        return (MA_ListViewDescribeResult) JSON.deserialize( res.getBody(), MA_ListViewDescribeResult.class );
    }

    // ------------------------------------------------------------------------

    /**
     * Given maps of source data whose keys match Mass_Action_Mapping__c.Source_Field_Name__c then
     * returns new maps whose keys match Mass_Action_Mapping__c.Target_Field_Name__c and whose values
     * match the source data. The returned maps will have as many keys as there are mappings.
     *
     * When considering a new source for Mass Action Service, then it is the source provider's
     * responsibility to transform its raw data format into source map format for reuse of this method.
     * For example, the report source and list view source classes handle their own transformations.
     */
    public static List<Map<String, Object>> buildActionInputs( List<Map<String, Object>> sourceRows, List<Mass_Action_Mapping__c> mappings ) {

        System.debug( 'MA_MassActionUtils.buildActionInputs' );
        System.debug( 'mappings: ' + mappings );
        System.debug( '----------' );

        List<Map<String, Object>> targetRows = new List<Map<String, Object>>();

        for ( Map<String, Object> sourceRow : sourceRows ) {

            Map<String, Object> targetRow = new Map<String, Object>();

            for ( Mass_Action_Mapping__c mapping : mappings ) {

                if ( !sourceRow.containsKey( mapping.source_field_name__c ) ) {
                    throw new MA_Exceptions.NoSourceFieldException( sourceRow, mapping.source_field_name__c );
                }

                targetRow.put( mapping.target_field_name__c, sourceRow.get( mapping.source_field_name__c ) );

            }

            System.debug( 'sourceRow: ' + sourceRow );
            System.debug( 'targetRow: ' + targetRow );
            System.debug( '----------' );

            targetRows.add( targetRow );

        }

        return targetRows;
    }

    // ------------------------------------------------------------------------

    /**
     * Invokes REST API via http callout.
     * https://developer.salesforce.com/docs/atlas.en-us.api_action.meta/api_action/actions_intro_invoking.htm
     */
    public static void invokeAction( String baseURL, Mass_Action_Configuration__c config, List<Map<String, Object>> targetRowMaps ) {

        System.debug( 'MA_MassActionUtils.invokeAction' );
        System.debug( 'config: ' + config );

        HttpRequest req = buildInvokeActionHttpRequest( baseURL, config, targetRowMaps );
        HttpResponse res = sendHttpRequest( req );

    }

    /**
     * Invokes REST API via http callout.
     * You call this method to get list of object names that can be used with getInvocableActions(..) method.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     */
    public static List<String> getObjectsWithInvocableActions( String baseURL, String actionType ) {

        System.debug( 'MA_MassActionUtils.getObjectsWithInvocableActions' );
        System.debug( 'baseURL: ' + baseURL );
        System.debug( 'actionType: ' + actionType );

        HttpRequest req = buildInvocableActionsHttpRequest( baseURL, actionType, EMPTY_STRING );
        HttpResponse res = sendHttpRequest( req );

        List<String> objectNames = parseActionObjectsHttpResponse( res );

        return objectNames;
    }

    /**
     * Invokes REST API via http callout.
     * You call this method to get list of available actions for given type and object.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param objectName
     *      API name of object whose actions to get of the given type (e.g. 'Account', 'Foo__c')
     */
    public static List<Map<String, Object>> getInvocableActions( String baseURL, String actionType, String objectName ) {

        System.debug( 'MA_MassActionUtils.getInvocableActions' );
        System.debug( 'baseURL: ' + baseURL );
        System.debug( 'actionType: ' + actionType );
        System.debug( 'objectName: ' + objectName );

        HttpRequest req = buildInvocableActionsHttpRequest( baseURL, actionType, objectName );
        HttpResponse res = sendHttpRequest( req );

        List<Map<String, Object>> actions = parseActionsHttpResponse( res );

        return actions;
    }

    /**
     * Gets the input variables for the given invocable action.
     * Use this to know what to prompt user for when binding source fields to target fields.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param actionName
     *      API Name of the invocable action whose inputs to request.
     * @param objectName
     *      API Name of the object whose action to request.
     */
    public static List<Map<String, Object>> getInvocableActionInputs( String baseURL, String actionType, String actionName, String objectName ) {

        System.debug( 'MA_MassActionUtils.getInvocableActionInputs' );
        System.debug( 'baseURL: ' + baseURL );
        System.debug( 'actionType: ' + actionType );
        System.debug( 'actionName: ' + actionName );
        System.debug( 'objectName: ' + objectName );

        HttpRequest req = buildInvocableActionInputsHttpRequest( baseURL, actionType, actionName, objectName );
        HttpResponse res = sendHttpRequest( req );

        List<Map<String, Object>> inputs = parseActionInputsHttpResponse( res );

        return inputs;
    }

    // ------------------------------------------------------------------------

    /**
     * Creates an HttpRequest with a configured enpoint to invoke the target action
     * per the configuration. Also sets common headers for an authorized JSON request.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param config
     *      Mass Action Configuration record.
     * @param targetRowMaps
     *      Field mappings from the data source (e.g. list view or report) and
     *      inputs to the target action (e.g. quick action, apex, process, etc.).
     */
    private static HttpRequest buildInvokeActionHttpRequest( String baseURL, Mass_Action_Configuration__c config, List<Map<String, Object>> targetRowMaps ) {

        HttpRequest req = new HttpRequest();
        req.setEndpoint( getInvokeActionHttpRequestEndpoint( baseURL, config ) );
        req.setBody( getInvokeActionHttpRequestBody( config, targetRowMaps ) );
        req.setMethod( 'POST' );
        req.setTimeout( 120000 ); // max wait of 2 mins
        req.setCompressed( true );
        req.setHeader( 'Content-Type', 'application/json' );
        req.setHeader( 'Accepts', 'application/json' );
        req.setHeader( 'Authorization', 'Bearer ' + UserInfo.getSessionId() );

        return req;
    }

    /**
     * Creates an endpoint URL to REST API to invoke the target action per the configuration.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param config
     *      Mass Action Configuration record.
     */
    private static String getInvokeActionHttpRequestEndpoint( String baseURL, Mass_Action_Configuration__c config ) {

        String endpoint = null;

        if ( 'Workflow' == config.target_type__c ) {

            endpoint = String.format(
                '{0}/process/rules',
                new String[] { baseURL }
            );

        } else if ( 'Flow' == config.target_type__c ) {

            endpoint = String.format(
                '{0}/actions/custom/flow/{1}',
                new String[] { baseURL, config.target_action_name__c }
            );

        } else if ( 'QuickAction' == config.target_type__c ) {

            endpoint = String.format(
                '{0}/actions/custom/quickAction/{1}/{2}',
                new String[] { baseURL, config.target_sobject_type__c, config.target_action_name__c }
            );

        } else if ( 'EmailAlert' == config.target_type__c ) {

            endpoint = String.format(
                '{0}/actions/custom/emailAlert/{1}/{2}',
                new String[] { baseURL, config.target_sobject_type__c, config.target_action_name__c }
            );

        } else if ( 'Apex' == config.target_type__c ) {

            endpoint = String.format(
                '{0}/actions/custom/apex/{1}',
                new String[] { baseURL, config.target_action_name__c }
            );

        }

        return endpoint;
    }

    private static String getInvokeActionHttpRequestBody( Mass_Action_Configuration__c config, List<Map<String, Object>> targetRowMaps ) {

        Set<String> processRulesAPI = new Set<String> {
            'Workflow'
        };

        Set<String> actionsAPI = new Set<String> {
            'Flow',
            'QuickAction',
            'EmailAlert',
            'Apex'
        };

        String body = null;

        if ( processRulesAPI.contains( config.target_type__c ) ) {

            body = getInvokeActionHttpRequestBody_ProcessRules( targetRowMaps );

        } else if ( actionsAPI.contains( config.target_type__c ) ) {

            body = getInvokeActionHttpRequestBody_Actions( targetRowMaps );

        }

        return body;
    }

    /**
     * Builds up the JSON request body for the REST Process Rules API.
     * This includes references under '/services/data/<version>/process/rules'
     * Like Workflow Rules.
     *
     * https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_process_rules_trigger.htm
     */
    private static String getInvokeActionHttpRequestBody_ProcessRules( List<Map<String, Object>> targetRowMaps ) {

        Set<ID> contextIds = new Set<ID>();

        // In all seriousness, for workflow actions then only
        // one mapping should exist with target field name of 'ContextId'.
        // Just in case I ever change that key name then just going to iterate
        // all keys in the map and add to our set.
        // But there should only be one key in the map regardless.
        for ( Map<String, Object> targetRow : targetRowMaps ) {
            for ( String key : targetRow.keySet() ) {
                contextIds.add( ID.valueOf( String.valueOf( targetRow.get( key ) ) ) );
            }
        }

        Map<String, Object> inputsRequest = new Map<String, Object>{
            'contextIds' => contextIds
        };

        return JSON.serializePretty( inputsRequest );
    }

    /**
     * Builds up the JSON request body for the REST Actions API.
     * This includes references under '/services/data/<version>/actions'
     * like Process Builder, Flows, Quick Actions, Email Alerts, and Invocable Apex.
     *
     * https://developer.salesforce.com/docs/atlas.en-us.api_action.meta/api_action/actions_intro_invoking.htm
     */
    private static String getInvokeActionHttpRequestBody_Actions( List<Map<String, Object>> targetRowMaps ) {

        Map<String, Object> inputsRequest = new Map<String, Object>{
            'inputs' => targetRowMaps
        };

        return JSON.serializePretty( inputsRequest );
    }

    // ------------------------------------------------------------------------

    /**
     * Creates an HttpRequest with a configured enpoint to retrieve invocable actions
     * for the given object accessible by the REST API. Also sets common headers for
     * an authorized JSON request.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param objectName
     *      API Name of the object whose actions to request.
     */
    private static HttpRequest buildInvocableActionsHttpRequest( String baseURL, String actionType, String objectName ) {

        HttpRequest req = new HttpRequest();
        req.setEndpoint( getInvocableActionsHttpRequestEndpoint( baseURL, actionType, objectName ) );
        req.setMethod( 'GET' );
        req.setTimeout( 120000 ); // max wait of 2 mins
        req.setCompressed( true );
        req.setHeader( 'Content-Type', 'application/json' );
        req.setHeader( 'Accepts', 'application/json' );
        req.setHeader( 'Authorization', 'Bearer ' + UserInfo.getSessionId() );

        return req;
    }

    /**
     * Creates an endpoint URL to retrieve invocable actions for the given object
     * accessible by the REST API. Also sets common headers for an authorized JSON request.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param objectName
     *      API Name of the object whose actions to request.
     */
    private static String getInvocableActionsHttpRequestEndpoint( String baseURL, String actionType, String objectName ) {

        String endpoint = null;

        if ( 'Flow' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/flow',
                new String[] { baseURL }
            );

        } else if ( 'QuickAction' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/quickAction/{1}',
                new String[] { baseURL, objectName }
            );

        } else if ( 'EmailAlert' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/emailAlert/{1}',
                new String[] { baseURL, objectName }
            );

        } else if ( 'Apex' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/apex',
                new String[] { baseURL }
            );

        }

        return endpoint;
    }

    // ------------------------------------------------------------------------

    /**
     * Creates an HttpRequest with a configured enpoint to retrieve inputs for an invocable action
     * for the given object accessible by the REST API. Also sets common headers for an authorized JSON request.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param actionName
     *      API Name of the invocable action whose inputs to request.
     * @param objectName
     *      API Name of the object whose action to request.
     */
    private static HttpRequest buildInvocableActionInputsHttpRequest( String baseURL, String actionType, String actionName, String objectName ) {

        HttpRequest req = new HttpRequest();
        req.setEndpoint( getInvocableActionInputsHttpRequestEndpoint( baseURL, actionType, actionName, objectName ) );
        req.setMethod( 'GET' );
        req.setTimeout( 120000 ); // max wait of 2 mins
        req.setCompressed( true );
        req.setHeader( 'Content-Type', 'application/json' );
        req.setHeader( 'Accepts', 'application/json' );
        req.setHeader( 'Authorization', 'Bearer ' + UserInfo.getSessionId() );

        return req;
    }

    /**
     * Creates an endpoint URL to retrieve inputs for an invocable action
     * for the given object accessible by the REST API. Also sets common headers for an authorized JSON request.
     *
     * @param baseURL
     *      The 'baseURL' parameter can either be a Named Credential (e.g. 'callout:YourNC'),
     *      or the full path, to REST API (e.g. 'https://yourdomain.my.salesforce.com/services/data/v44.0').
     * @param actionType
     *      Value from picklist Mass_Action_Configuration__c.Target_Type__c (e.g. 'QuickAction', 'EmailAlert')
     * @param actionName
     *      API Name of the invocable action whose inputs to request.
     * @param objectName
     *      API Name of the object whose action to request.
     */
    private static String getInvocableActionInputsHttpRequestEndpoint( String baseURL, String actionType, String actionName, String objectName ) {

        String endpoint = null;

        if ( 'Flow' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/flow/{1}',
                new String[] { baseURL, actionName }
            );

        } else if ( 'QuickAction' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/quickAction/{1}/{2}',
                new String[] { baseURL, objectName, actionName }
            );

        } else if ( 'EmailAlert' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/emailAlert/{1}/{2}',
                new String[] { baseURL, objectName, actionName }
            );

        } else if ( 'Apex' == actionType ) {

            endpoint = String.format(
                '{0}/actions/custom/apex/{1}',
                new String[] { baseURL, actionName }
            );

        }

        return endpoint;
    }

    // ------------------------------------------------------------------------

    /**
     * Sends the http request and returns the http response.
     * Logs the request/response.
     * Throws exception if status code is not 200 OK.
     */
    private static HttpResponse sendHttpRequest( HttpRequest req ) {

        System.debug( req );
        System.debug( req.getBody() );

        HttpResponse res = new Http().send( req );

        System.debug( res );
        System.debug( res.getBody() );

        for ( String header : res.getHeaderKeys() ) {
            System.debug( header + '=' + res.getHeader( header ) );
        }

        if ( res.getStatusCode() != 200 ) {
            throw new MA_Exceptions.InvokeActionException( req, res );
        }

        return res;
    }

    // ------------------------------------------------------------------------

    /**
     * JSON deserializes the response and converts the map of key-value pairs into a list of keys.
     */
    private static List<String> parseActionObjectsHttpResponse( HttpResponse res ) {

        List<String> objectNames = new List<String>();

        Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped( res.getBody() );

        for ( String objectName : resMap.keySet() ) {
            objectNames.add( objectName );
        }

        return objectNames;
    }

    /**
     * JSON deserializes the 'actions' property of the response.
     */
    private static List<Map<String, Object>> parseActionsHttpResponse( HttpResponse res ) {

        List<Map<String, Object>> actions = new List<Map<String, Object>>();

        Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped( res.getBody() );

        List<Object> actionRecords = (List<Object>) resMap.get( 'actions' );

        for ( Object actionRecord : actionRecords ) {
            actions.add( (Map<String, Object>) actionRecord );
        }

        return actions;
    }

    /**
     * JSON deserializes the 'inputs' property of the response.
     */
    private static List<Map<String, Object>> parseActionInputsHttpResponse( HttpResponse res ) {

        List<Map<String, Object>> inputs = new List<Map<String, Object>>();

        Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped( res.getBody() );

        List<Object> inputRecords = (List<Object>) resMap.get( 'inputs' );

        for ( Object inputRecord : inputRecords ) {
            inputs.add( (Map<String, Object>) inputRecord );
        }

        return inputs;
    }

}
/*
BSD 3-Clause License

Copyright (c) 2018, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/